package org.shiro.forge2.model;
// Generated 08/07/2015 16:21:40 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import org.hibernate.validator.constraints.NotBlank;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name="user"
    ,catalog="shiro_forge2"
    , uniqueConstraints = @UniqueConstraint(columnNames="login") 
)
public class User  implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Integer id;
     @NotBlank
     private String name;
     @NotBlank
     private String email;
     @NotBlank
     private String login;
     @NotBlank
     private String password;

    public User() {
    }

    public User(String name, String email, String login, String password) {
       this.name = name;
       this.email = email;
       this.login = login;
       this.password = password;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="name", nullable=false, length=80)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="email", nullable=false, length=150)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="login", unique=true, nullable=false, length=16)
    public String getLogin() {
        return this.login;
    }
    
    public void setLogin(String login) {
        this.login = login;
    }

    
    @Column(name="password", nullable=false, length=100)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }




}


